var levels = {
    level1:{
        main:{
            background:{
                top:0,
                left:0,
                width:0,
                height:0,
                opacity:0
            },
            runner:{
                top:0,
                left:0,
                width:0,
                height:0
            },
            platforms:[
                {
                    top:0,
                    left:0,
                    width:0,
                    height:0
                }
            ]
        }
    }
}